# Generated by Django 4.1.3 on 2022-12-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='divans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mod', models.CharField(max_length=100)),
                ('cost', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
