# Generated by Django 4.1.3 on 2022-12-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_divans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divans',
            old_name='mod',
            new_name='color',
        ),
    ]
