# Generated by Django 4.1.3 on 2022-12-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_mod_divans_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('cost', models.PositiveSmallIntegerField(verbose_name='Цена')),
            ],
        ),
        migrations.AlterField(
            model_name='divans',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='divans',
            name='cost',
            field=models.PositiveSmallIntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='divans',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
