# Generated by Django 4.1.3 on 2022-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
        migrations.AddField(
            model_name='divans',
            name='image',
            field=models.ImageField(blank=True, upload_to='myapp/static'),
        ),
    ]
